### PR TITLE
Fixed compilation issues

### PR DESCRIPTION
**Pull request by dancollins**
I had trouble compiling this on Ubuntu 16.04.2 LTS with GCC 5.4.0. I
went through these issues, removing errors and silencing warnings.

### CODE REVIEW

**Comment by dancollins** [comment]
If you prefer, I can remove the warning suppression and fix the warnings. This would be a simple matter of going through and deleting the unused variables.

I have tested this using xterm, and it seems to work well!

**Comment by emilwallner** [comment]
@dancollins Thanks!! That'd be ace! I get this issue when I run your version: `error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]`

**Comment by dancollins** [comment]
Interesting. Which GCC version are you running? I will remove this warning suppression and fix the warning instead.

**Comment by emilwallner** [comment]
Cool, I'm on OS X 10.11.6. Mac started with clang a while ago: Apple LLVM version 8.0.0 (clang-800.0.38).

**Comment by emilwallner** [comment]
@dancollins Legend, thanks! 🍻

**Pull request merged**
